### ISSUE TITLE
How do I utilize this package to run this script everytime I load a website?

### ISSUE THREAD

**Issue by dmxt** [github/g-emoji-element#22]
Is a `web-extension` the only way? If so, how do I exactly port these files to Chrome manifested extension? Does it detect the DOM updater with new emoji?

**Comment by keithamus** [comment]
Thanks for the issue @dmxt!

This issue tracker is only for bugs in the `g-emoji-element` library. We're unable to help you with support requests, such as how to use it - beyond what the README offers. You might want to visit a Q&A site like https://stackoverflow.com/ where people may be able to help you.

I'll close this, as it isn't an actionable bug. Thanks for understanding!
