### ISSUE TITLE
Write an actual test for emoji support

### ISSUE THREAD

**Issue by Crissov** [github/g-emoji-element#6]
In `emoji-detection.js`, this is currently just looking for one of the strings `Windows NT 6.1`, `Windows NT 6.2`, `Windows NT 6.3`,  `Linux` and `FreeBSD` in `navigator.userAgent`. This is too naive: some people running Linux configure their system to successfully display even the latest emojis, some people running old Windows versions have a browser plugin that inserts new emojis, while some other OSes also do not support emojis. Use [some explicit test](https://about.gitlab.com/2018/05/30/journey-in-native-unicode-emoji/) instead.

**Comment by muan** [comment]
As explained in https://github.com/github/g-emoji-element/pull/19#issuecomment-539405274, this was intentional.
